apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-backend
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-backend
  template:
    metadata:
      labels:
        app: portfolio-backend
    spec:
      containers:
        - name: portfolio-backend
          image: pillyigshankar/portfolio-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            # --------- DATABASE CONFIG -----------
            # This overrides spring.datasource.url in properties
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/portfolio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

            # These fill ${DB_USER} and ${DB_PASS}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: db-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: db-pass

            # --------- MAIL CONFIG -----------
            # for now you can hardcode or also put in a separate secret
            - name: MAIL_USER
              value: "yourgmailid@gmail.com"
            - name: MAIL_PASS
              value: "your_gmail_app_password"

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-backend
  namespace: portfolio
spec:
  selector:
    app: portfolio-backend
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30025
  type: NodePort
